#!/usr/bin/env sh
#. "$(dirname -- "$0")/h"

# Cores
NC='\033[0m'
BBlue='\033[1;34m'
BRed='\033[1;31m'

REGEX_ISSUE_ID="[a-zA-Z0-9,._-]+-[0-9]+"
BRANCH_NAME=$(git symbolic-ref --short HEAD)
ISSUE_ID=$(echo "$BRANCH_NAME" | grep -o -E "$REGEX_ISSUE_ID")

if [ -z "$ISSUE_ID" ]; then
    echo -e "${BRed}Branch não está no padrão que deveria mestre... ${NC}"
    exit 1
fi

if [ -z "$1" ]; then
    echo -e "${BRed}Mensagem de commit não fornecida. ${NC}"
    exit 1
fi

COMMIT_MESSAGE=$(cat "$1")

# Verificar se o COMMIT_MESSAGE começa com ISSUE_ID
if echo "$COMMIT_MESSAGE" | grep -q "^$ISSUE_ID"; then
    exit 0
fi

echo "$ISSUE_ID: $COMMIT_MESSAGE" > "$1"
